### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by SaraVieira** [OpenSourceLove/design#1]
Hey Guys !

Do you guys like this idea for a logo ?

<img width="866" alt="screenshot 2017-07-07 21 40 51" src="https://user-images.githubusercontent.com/1051509/27976112-12d6e212-635d-11e7-89dd-6b2724686b9b.png">

**Comment by eduardoboucas** [comment]
I like it!

**Comment by SaraVieira** [comment]
Awesome! This will of course be open source and anyone can change the sketch file:D

@sapegin watchu think?

**Comment by sapegin** [comment]
I’d try to make the bottom of the heart less curvy and move gray thing a bit up ;-)

**Comment by SaraVieira** [comment]
Somthing like this ?

<img width="744" alt="screenshot 2017-07-10 10 17 03" src="https://user-images.githubusercontent.com/1051509/28011055-f38cccfc-6558-11e7-8994-18dd5703e7d6.png">

I also removed the border as it looked horrible when the logo was smaller

cc @eduardoboucas @sapegin

**Comment by sapegin** [comment]
Better! But I thing the hart should be more “circular” than “curvy” to better match the gray thing ;-)

**Comment by SaraVieira** [comment]
Oh ! Got it ! I will try to achieve that after kunch and post updates here :)

**Comment by jorgemartins** [comment]
Hey guys, finally had some time to play around this and came up with this idea: #3 
![osl-v2](https://user-images.githubusercontent.com/1323193/29099574-1fe35d96-7c9e-11e7-991f-dbd29bbde442.png)

it is basically re-interpreting Sara's concept while abstracting it a little bit.
let me know what you think, cc/ @SaraVieira @eduardoboucas @sapegin

**Comment by sapegin** [comment]
Bu why a keyhole? This looks like closed source love ;-) But I like the sign itself ;-)

**Comment by SaraVieira** [comment]
@sapegin The keyhole is actually taken from the open source initiave : https://opensource.org/logo-usage-guidelines

That's why I used it too


@jorgemartins It looks way better than mine ! Awesome 👍  🎉

**Comment by sapegin** [comment]
So you can see the source through a keyhole? That’s smart ;-)

**Comment by SaraVieira** [comment]
@sapegin See ? That was pretty deep ! ❤️  🎉 

I'm okay to stay with this , it looks awesome!

cc @eduardoboucas 

@jorgemartins Can you creat a color pallete with tgis logo in mind so we can work with that pallete in the website ?

**Comment by eduardoboucas** [comment]
I like it! Personally I think I'd go for warmer colours, like the initial red or similar, to emphasise the love feeling. But maybe the blue works too.

**Comment by SaraVieira** [comment]
I'll talk to @jorgemartins as soon as he gets back from lunch abut that . Thanks @eduardoboucas

**Comment by jorgemartins** [comment]
thanks for the feedback 🙌  
I like the idea of making it warmer! great suggestion.
I ended up doing two versions anyway, let me know how you guys feel about them.

![opensourcelove_bright](https://user-images.githubusercontent.com/1323193/29149659-8cd477c6-7d6d-11e7-8588-e83d19325871.png) ![opensourcelove_warm](https://user-images.githubusercontent.com/1323193/29149660-8f5ad080-7d6d-11e7-8e59-8884b30b77ab.png)

as you notice, I also changed the color on love, so it gets his proper attention.

(Personally, I like the Warmer tones better, so I already created some variations in sizes as well as the 1color version, that it may or may not be needed. Was fun to make though 👍 )
![open source love - logo variations](https://user-images.githubusercontent.com/1323193/29149777-3850396e-7d6e-11e7-8c02-2aa8cf63879b.png)

**Comment by sapegin** [comment]
I like single-color version!

**Comment by SaraVieira** [comment]
@sapegin wich one do you mean? 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sapegin** [comment]
The one marked as “one color logotype”, the last one.

**Comment by SaraVieira** [comment]
Weirdly enough me too! It looks simple and great! 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SaraVieira** [comment]
@eduardoboucas 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by eduardoboucas** [comment]
My favourite is the one labelled as "Logo icon", as it works on all size variations. Especially on small sizes, it looks like a traditional FB/Twitter heart but with our own twist, which I quite like.

I don't mind the other one either, though. :)

**Comment by SaraVieira** [comment]
@jorgemartins, your say? 

_Sent from my Bq Aquaris M5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jorgemartins** [comment]
Cool !
A bit of context, that last image wasn't supposed to be 3 diff versions, the idea was that there is one logo and color scheme that can be applied in those 3 diff ways:
1. _**just the icon**_ [to be used as favicon, buttons (like Eduardo mentioned) or stickers (thinking of you @SaraVieira 😀 )]
2. _**icon + type**_ [to be used elsewhere, like page header/footer, other sites that might link to this project]
— having the type is also helpful at the first time a person sees it, as it is the actual name of the project
— there still can be some cases where it is ok to just use the type without the icon, so it's always nice to have
3. _**single-color**_ [to be used in too dark or too bright background scenarios (see how github uses the single-color octocat in the footer although they have a colored version too -> :octocat: ) ]

I'd say this is closed as it seems we all liked the symbol/icon/logo and all the rest is just about how/when it is applied 👍 

But just to be very sure, we all like/Agree with this color scheme? (it doesn't mean the whole site is going to have this colors, they are just like accent colors)

![open source love - logo variations](https://user-images.githubusercontent.com/1323193/29168620-8220fc00-7dc7-11e7-99df-a3e25a078600.png)

**Comment by SaraVieira** [comment]
@jorgemartins I'm all up for stickers and closing this !

**Comment by sapegin** [comment]
+1 from me!

**Comment by SaraVieira** [comment]
Closed and fixed by #3
